version: '1.0'

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: online_store
        ports:
            - 5432:5432

    api:
        image: auliardanaa/online-store-api:be-online-store-api
        container_name: be-online-store-api
        build: .
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - postgres
